//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crystalbyte.Asphalt.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crystalbyte.Asphalt.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asphalt.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASPHALT.
        /// </summary>
        public static string ApplicationTitleCapital {
            get {
                return ResourceManager.GetString("ApplicationTitleCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new reason for the current tour..
        /// </summary>
        public static string ChangeReasonPopupText {
            get {
                return ResourceManager.GetString("ChangeReasonPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteMenuHeader {
            get {
                return ResourceManager.GetString("DeleteMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string DestinationLabelText {
            get {
                return ResourceManager.GetString("DestinationLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string DistanceLabelText {
            get {
                return ResourceManager.GetString("DistanceLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated current mileage.
        /// </summary>
        public static string EstimatedMileageLabelText {
            get {
                return ResourceManager.GetString("EstimatedMileageLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Querying route ....
        /// </summary>
        public static string EstimatingRoute {
            get {
                return ResourceManager.GetString("EstimatingRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression is not a member access expression.
        /// </summary>
        public static string ExpressionNoMember {
            get {
                return ResourceManager.GetString("ExpressionNoMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient data.
        /// </summary>
        public static string InsufficientDataCaption {
            get {
                return ResourceManager.GetString("InsufficientDataCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current recording yielded insufficient data and will be discarded..
        /// </summary>
        public static string InsufficientDataMessage {
            get {
                return ResourceManager.GetString("InsufficientDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The label must not be empty.
        /// </summary>
        public static string LabelNotNullOrEmpty {
            get {
                return ResourceManager.GetString("LabelNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The licence plate must not be empty.
        /// </summary>
        public static string LicencePlateNotNullOrEmpty {
            get {
                return ResourceManager.GetString("LicencePlateNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ....
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member access expression does not access a property.
        /// </summary>
        public static string MemberExpressionNoProperty {
            get {
                return ResourceManager.GetString("MemberExpressionNoProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin.
        /// </summary>
        public static string OriginLabelText {
            get {
                return ResourceManager.GetString("OriginLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string ReasonLabelText {
            get {
                return ResourceManager.GetString("ReasonLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The referenced property is a static property.
        /// </summary>
        public static string ReferencedPropertyIsStatic {
            get {
                return ResourceManager.GetString("ReferencedPropertyIsStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Route.
        /// </summary>
        public static string RouteLabelText {
            get {
                return ResourceManager.GetString("RouteLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsMenuItemText {
            get {
                return ResourceManager.GetString("SettingsMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin.
        /// </summary>
        public static string StartTimeLabelText {
            get {
                return ResourceManager.GetString("StartTimeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string StopTimeLabelText {
            get {
                return ResourceManager.GetString("StopTimeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to change.
        /// </summary>
        public static string TapToChangeText {
            get {
                return ResourceManager.GetString("TapToChangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tours.
        /// </summary>
        public static string ToursPanoramaPageHeaderText {
            get {
                return ResourceManager.GetString("ToursPanoramaPageHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TourTypeLabelText {
            get {
                return ResourceManager.GetString("TourTypeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tracking.
        /// </summary>
        public static string TrackingPanoramaItemTitle {
            get {
                return ResourceManager.GetString("TrackingPanoramaItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the preferred unit of length for displaying distances.
        /// </summary>
        public static string UnitOfLengthDescriptionText {
            get {
                return ResourceManager.GetString("UnitOfLengthDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of length.
        /// </summary>
        public static string UnitOfLengthSettingsText {
            get {
                return ResourceManager.GetString("UnitOfLengthSettingsText", resourceCulture);
            }
        }
    }
}
