//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crystalbyte.Asphalt.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crystalbyte.Asphalt.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add photo.
        /// </summary>
        public static string AddDriverImageText {
            get {
                return ResourceManager.GetString("AddDriverImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add driver.
        /// </summary>
        public static string AddDriverLandingButtonText {
            get {
                return ResourceManager.GetString("AddDriverLandingButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add driver.
        /// </summary>
        public static string AddDriverPageTitle {
            get {
                return ResourceManager.GetString("AddDriverPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AddVehicleButtonText {
            get {
                return ResourceManager.GetString("AddVehicleButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add vehicle.
        /// </summary>
        public static string AddVehicleLandingButtonText {
            get {
                return ResourceManager.GetString("AddVehicleLandingButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add vehicle.
        /// </summary>
        public static string AddVehiclePageTitle {
            get {
                return ResourceManager.GetString("AddVehiclePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add photo.
        /// </summary>
        public static string AddVehiclePhotoText {
            get {
                return ResourceManager.GetString("AddVehiclePhotoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asphalt.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASPHALT.
        /// </summary>
        public static string ApplicationTitleCapital {
            get {
                return ResourceManager.GetString("ApplicationTitleCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        public static string Business {
            get {
                return ResourceManager.GetString("Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commit.
        /// </summary>
        public static string CommitSettingsButtonText {
            get {
                return ResourceManager.GetString("CommitSettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commute.
        /// </summary>
        public static string Commute {
            get {
                return ResourceManager.GetString("Commute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commute.
        /// </summary>
        public static string CommuteReasonText {
            get {
                return ResourceManager.GetString("CommuteReasonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confirm.
        /// </summary>
        public static string ConfirmButtonText {
            get {
                return ResourceManager.GetString("ConfirmButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danger zone.
        /// </summary>
        public static string DangerZoneText {
            get {
                return ResourceManager.GetString("DangerZoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string DeleteButtonText {
            get {
                return ResourceManager.GetString("DeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete driver?.
        /// </summary>
        public static string DeleteDriverConfirmCaption {
            get {
                return ResourceManager.GetString("DeleteDriverConfirmCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action cannot be undone..
        /// </summary>
        public static string DeleteDriverConfirmMessage {
            get {
                return ResourceManager.GetString("DeleteDriverConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteMenuHeader {
            get {
                return ResourceManager.GetString("DeleteMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete tour?.
        /// </summary>
        public static string DeleteRouteConfirmCaption {
            get {
                return ResourceManager.GetString("DeleteRouteConfirmCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action cannot be undone..
        /// </summary>
        public static string DeleteRouteConfirmMessage {
            get {
                return ResourceManager.GetString("DeleteRouteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete vehicle?.
        /// </summary>
        public static string DeleteVehicleConfirmCaption {
            get {
                return ResourceManager.GetString("DeleteVehicleConfirmCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action cannot be undone..
        /// </summary>
        public static string DeleteVehicleConfirmMessage {
            get {
                return ResourceManager.GetString("DeleteVehicleConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string DestinationLabel {
            get {
                return ResourceManager.GetString("DestinationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string DistanceLabel {
            get {
                return ResourceManager.GetString("DistanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not change the values below unless you know exactly what you&apos;re doing. Incorrect settings may decrease accuracy or impair functionality..
        /// </summary>
        public static string DoNotChangeText {
            get {
                return ResourceManager.GetString("DoNotChangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        public static string DriverLabel {
            get {
                return ResourceManager.GetString("DriverLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drivers.
        /// </summary>
        public static string DriversPanoramaPageHeaderText {
            get {
                return ResourceManager.GetString("DriversPanoramaPageHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string DurationLabel {
            get {
                return ResourceManager.GetString("DurationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string EditSettingsButtonText {
            get {
                return ResourceManager.GetString("EditSettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string EditVehicleButtonText {
            get {
                return ResourceManager.GetString("EditVehicleButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to export data.
        /// </summary>
        public static string ErrorExportingDataCaption {
            get {
                return ResourceManager.GetString("ErrorExportingDataCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update database.
        /// </summary>
        public static string ErrorUpdatingDatabase {
            get {
                return ResourceManager.GetString("ErrorUpdatingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Querying route ....
        /// </summary>
        public static string EstimatingRoute {
            get {
                return ResourceManager.GetString("EstimatingRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to export.
        /// </summary>
        public static string ExportButtonText {
            get {
                return ResourceManager.GetString("ExportButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export location.
        /// </summary>
        public static string ExportDestinationLabel {
            get {
                return ResourceManager.GetString("ExportDestinationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File format.
        /// </summary>
        public static string ExportFormatLabel {
            get {
                return ResourceManager.GetString("ExportFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to export.
        /// </summary>
        public static string ExportPageTitle {
            get {
                return ResourceManager.GetString("ExportPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting data ....
        /// </summary>
        public static string ExportStateCollectingText {
            get {
                return ResourceManager.GetString("ExportStateCollectingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload successfully completed.
        /// </summary>
        public static string ExportStateCompletedText {
            get {
                return ResourceManager.GetString("ExportStateCompletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading ....
        /// </summary>
        public static string ExportStateUploadingText {
            get {
                return ResourceManager.GetString("ExportStateUploadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression is not a member access expression.
        /// </summary>
        public static string ExpressionNoMember {
            get {
                return ResourceManager.GetString("ExpressionNoMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forename.
        /// </summary>
        public static string ForenameLabel {
            get {
                return ResourceManager.GetString("ForenameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The forename must not be empty..
        /// </summary>
        public static string ForenameNotNullOrEmpty {
            get {
                return ResourceManager.GetString("ForenameNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mileage must not be empty..
        /// </summary>
        public static string InitialMileageNotNullOrEmpty {
            get {
                return ResourceManager.GetString("InitialMileageNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient data.
        /// </summary>
        public static string InsufficientDataCaption {
            get {
                return ResourceManager.GetString("InsufficientDataCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current recording yielded insufficient results and will be discarded..
        /// </summary>
        public static string InsufficientDataMessage {
            get {
                return ResourceManager.GetString("InsufficientDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License plate.
        /// </summary>
        public static string LicensePlateLabel {
            get {
                return ResourceManager.GetString("LicensePlateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The license plate must not be empty.
        /// </summary>
        public static string LicensePlateNotNullOrEmpty {
            get {
                return ResourceManager.GetString("LicensePlateNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ....
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member access expression does not access a property.
        /// </summary>
        public static string MemberExpressionNoProperty {
            get {
                return ResourceManager.GetString("MemberExpressionNoProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mileage.
        /// </summary>
        public static string MileageLabel {
            get {
                return ResourceManager.GetString("MileageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mileage before.
        /// </summary>
        public static string MileageOnStartLabel {
            get {
                return ResourceManager.GetString("MileageOnStartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mileage after.
        /// </summary>
        public static string MileageOnStopLabel {
            get {
                return ResourceManager.GetString("MileageOnStopLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app will automatically record your tours based on your travelling speed..
        /// </summary>
        public static string MovementDetectionDescription {
            get {
                return ResourceManager.GetString("MovementDetectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automated tour recording.
        /// </summary>
        public static string MovementDetectionLabel {
            get {
                return ResourceManager.GetString("MovementDetectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no tours selected for export..
        /// </summary>
        public static string NoExportText {
            get {
                return ResourceManager.GetString("NoExportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string NotesLabel {
            get {
                return ResourceManager.GetString("NotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin.
        /// </summary>
        public static string OriginLabel {
            get {
                return ResourceManager.GetString("OriginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private tour.
        /// </summary>
        public static string PrivateReasonText {
            get {
                return ResourceManager.GetString("PrivateReasonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to get started, you need to add a driver and a vehicle..
        /// </summary>
        public static string QuickInfo {
            get {
                return ResourceManager.GetString("QuickInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact / Reason.
        /// </summary>
        public static string ReasonLabel {
            get {
                return ResourceManager.GetString("ReasonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason not specified.
        /// </summary>
        public static string ReasonNotSpecified {
            get {
                return ResourceManager.GetString("ReasonNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason not specified.
        /// </summary>
        public static string ReasonNotSpecifiedWatermark {
            get {
                return ResourceManager.GetString("ReasonNotSpecifiedWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string RecordingTimeoutLabel {
            get {
                return ResourceManager.GetString("RecordingTimeoutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start recording?.
        /// </summary>
        public static string RecordRouteConfirmCaption {
            get {
                return ResourceManager.GetString("RecordRouteConfirmCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone&apos;s geolocator will record your route until you manually press the stop button..
        /// </summary>
        public static string RecordRouteConfirmMessage {
            get {
                return ResourceManager.GetString("RecordRouteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The referenced property is a static property.
        /// </summary>
        public static string ReferencedPropertyIsStatic {
            get {
                return ResourceManager.GetString("ReferencedPropertyIsStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geolocation report interval.
        /// </summary>
        public static string ReportIntervalLabel {
            get {
                return ResourceManager.GetString("ReportIntervalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required GPS accuracy.
        /// </summary>
        public static string RequiredAccuracyLabel {
            get {
                return ResourceManager.GetString("RequiredAccuracyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restore factory settings.
        /// </summary>
        public static string ResetSettingsMenuText {
            get {
                return ResourceManager.GetString("ResetSettingsMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The displayed route is only an approximation and not used on calculations..
        /// </summary>
        public static string RouteDescription {
            get {
                return ResourceManager.GetString("RouteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route.
        /// </summary>
        public static string RouteLabel {
            get {
                return ResourceManager.GetString("RouteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string SaveVehicleButtonText {
            get {
                return ResourceManager.GetString("SaveVehicleButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select.
        /// </summary>
        public static string SelectionButtonText {
            get {
                return ResourceManager.GetString("SelectionButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsMenuItemText {
            get {
                return ResourceManager.GetString("SettingsMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is 1 tour selected for export..
        /// </summary>
        public static string SingleExportText {
            get {
                return ResourceManager.GetString("SingleExportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign in using your SkyDrive credentials..
        /// </summary>
        public static string SkyDriveLoginText {
            get {
                return ResourceManager.GetString("SkyDriveLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed samples required.
        /// </summary>
        public static string SpeedExceedancesLabel {
            get {
                return ResourceManager.GetString("SpeedExceedancesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string SpeedLabel {
            get {
                return ResourceManager.GetString("SpeedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed exceedance threshold.
        /// </summary>
        public static string SpeedThresholdLabel {
            get {
                return ResourceManager.GetString("SpeedThresholdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start recording a new tour.
        /// </summary>
        public static string StartButtonDescriptionText {
            get {
                return ResourceManager.GetString("StartButtonDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartButtonText {
            get {
                return ResourceManager.GetString("StartButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string StartExportButtonText {
            get {
                return ResourceManager.GetString("StartExportButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin.
        /// </summary>
        public static string StartTimeLabel {
            get {
                return ResourceManager.GetString("StartTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminate current recording.
        /// </summary>
        public static string StopButtonDescriptionText {
            get {
                return ResourceManager.GetString("StopButtonDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string StopButtonText {
            get {
                return ResourceManager.GetString("StopButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string StopTimeLabel {
            get {
                return ResourceManager.GetString("StopTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string SurnameLabel {
            get {
                return ResourceManager.GetString("SurnameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The surname must not be empty..
        /// </summary>
        public static string SurnameNotNullOrEmpty {
            get {
                return ResourceManager.GetString("SurnameNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminate recording?.
        /// </summary>
        public static string TerminateRouteConfirmCaption {
            get {
                return ResourceManager.GetString("TerminateRouteConfirmCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A terminated recording cannot be resumed..
        /// </summary>
        public static string TerminateRouteConfirmMessage {
            get {
                return ResourceManager.GetString("TerminateRouteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} tours selected for export..
        /// </summary>
        public static string TourExportsFormatString {
            get {
                return ResourceManager.GetString("TourExportsFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tours.
        /// </summary>
        public static string ToursPanoramaPageHeaderText {
            get {
                return ResourceManager.GetString("ToursPanoramaPageHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TourTypeLabel {
            get {
                return ResourceManager.GetString("TourTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recording.
        /// </summary>
        public static string TrackingPanoramaItemTitle {
            get {
                return ResourceManager.GetString("TrackingPanoramaItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial mode enables you to export only a single item at a time..
        /// </summary>
        public static string TrialExportLimitationText {
            get {
                return ResourceManager.GetString("TrialExportLimitationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the preferred unit of length..
        /// </summary>
        public static string UnitOfLengthDescriptionText {
            get {
                return ResourceManager.GetString("UnitOfLengthDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of length.
        /// </summary>
        public static string UnitOfLengthSettingsText {
            get {
                return ResourceManager.GetString("UnitOfLengthSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        public static string VehicleLabel {
            get {
                return ResourceManager.GetString("VehicleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vehicles.
        /// </summary>
        public static string VehiclesPanoramaPageHeaderText {
            get {
                return ResourceManager.GetString("VehiclesPanoramaPageHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start recordings manually or let Asphalt handle it for you..
        /// </summary>
        public static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
    }
}
