//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crystalbyte.Asphalt.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crystalbyte.Asphalt.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AddVehicleButtonText {
            get {
                return ResourceManager.GetString("AddVehicleButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add vehicle.
        /// </summary>
        public static string AddVehiclePageTitle {
            get {
                return ResourceManager.GetString("AddVehiclePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add photo.
        /// </summary>
        public static string AddVehiclePhotoText {
            get {
                return ResourceManager.GetString("AddVehiclePhotoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asphalt.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASPHALT.
        /// </summary>
        public static string ApplicationTitleCapital {
            get {
                return ResourceManager.GetString("ApplicationTitleCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new reason for the current tour..
        /// </summary>
        public static string ChangeReasonPopupText {
            get {
                return ResourceManager.GetString("ChangeReasonPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string DeleteButtonText {
            get {
                return ResourceManager.GetString("DeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteMenuHeader {
            get {
                return ResourceManager.GetString("DeleteMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete tour?.
        /// </summary>
        public static string DeleteRouteConfirmCaption {
            get {
                return ResourceManager.GetString("DeleteRouteConfirmCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A deleted tour cannot be recovered..
        /// </summary>
        public static string DeleteRouteConfirmMessage {
            get {
                return ResourceManager.GetString("DeleteRouteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string DestinationLabel {
            get {
                return ResourceManager.GetString("DestinationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string DistanceLabel {
            get {
                return ResourceManager.GetString("DistanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drivers.
        /// </summary>
        public static string DriversPanoramaPageHeaderText {
            get {
                return ResourceManager.GetString("DriversPanoramaPageHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string EditVehicleButtonText {
            get {
                return ResourceManager.GetString("EditVehicleButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Querying route ....
        /// </summary>
        public static string EstimatingRoute {
            get {
                return ResourceManager.GetString("EstimatingRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to export.
        /// </summary>
        public static string ExportButtonText {
            get {
                return ResourceManager.GetString("ExportButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to export.
        /// </summary>
        public static string ExportPageTitle {
            get {
                return ResourceManager.GetString("ExportPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression is not a member access expression.
        /// </summary>
        public static string ExpressionNoMember {
            get {
                return ResourceManager.GetString("ExpressionNoMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mileage must not be empty..
        /// </summary>
        public static string InitialMileageNotNullOrEmpty {
            get {
                return ResourceManager.GetString("InitialMileageNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient data.
        /// </summary>
        public static string InsufficientDataCaption {
            get {
                return ResourceManager.GetString("InsufficientDataCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current recording yielded insufficient data and will be discarded..
        /// </summary>
        public static string InsufficientDataMessage {
            get {
                return ResourceManager.GetString("InsufficientDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The label must not be empty.
        /// </summary>
        public static string LabelNotNullOrEmpty {
            get {
                return ResourceManager.GetString("LabelNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The licence plate must not be empty.
        /// </summary>
        public static string LicencePlateNotNullOrEmpty {
            get {
                return ResourceManager.GetString("LicencePlateNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ....
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member access expression does not access a property.
        /// </summary>
        public static string MemberExpressionNoProperty {
            get {
                return ResourceManager.GetString("MemberExpressionNoProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mileage.
        /// </summary>
        public static string MileageLabel {
            get {
                return ResourceManager.GetString("MileageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app will automatically start and stop recordings for new routes based on you traveling speed..
        /// </summary>
        public static string MovementDetectionDescription {
            get {
                return ResourceManager.GetString("MovementDetectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automated movement detection.
        /// </summary>
        public static string MovementDetectionLabel {
            get {
                return ResourceManager.GetString("MovementDetectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no photo.
        /// </summary>
        public static string NoVehiclePhotoText {
            get {
                return ResourceManager.GetString("NoVehiclePhotoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin.
        /// </summary>
        public static string OriginLabel {
            get {
                return ResourceManager.GetString("OriginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string ReasonLabel {
            get {
                return ResourceManager.GetString("ReasonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason not specified.
        /// </summary>
        public static string ReasonNotSpecified {
            get {
                return ResourceManager.GetString("ReasonNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start recording?.
        /// </summary>
        public static string RecordRouteConfirmCaption {
            get {
                return ResourceManager.GetString("RecordRouteConfirmCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone&apos;s geolocator will record your route until you manually press the stop button..
        /// </summary>
        public static string RecordRouteConfirmMessage {
            get {
                return ResourceManager.GetString("RecordRouteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The referenced property is a static property.
        /// </summary>
        public static string ReferencedPropertyIsStatic {
            get {
                return ResourceManager.GetString("ReferencedPropertyIsStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Route.
        /// </summary>
        public static string RouteLabel {
            get {
                return ResourceManager.GetString("RouteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select.
        /// </summary>
        public static string SelectionButtonText {
            get {
                return ResourceManager.GetString("SelectionButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsMenuItemText {
            get {
                return ResourceManager.GetString("SettingsMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string SpeedLabel {
            get {
                return ResourceManager.GetString("SpeedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin.
        /// </summary>
        public static string StartTimeLabel {
            get {
                return ResourceManager.GetString("StartTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string StopTimeLabel {
            get {
                return ResourceManager.GetString("StopTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminate route?.
        /// </summary>
        public static string TerminateRouteConfirmCaption {
            get {
                return ResourceManager.GetString("TerminateRouteConfirmCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A terminated route cannot be resumed..
        /// </summary>
        public static string TerminateRouteConfirmMessage {
            get {
                return ResourceManager.GetString("TerminateRouteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tours.
        /// </summary>
        public static string ToursPanoramaPageHeaderText {
            get {
                return ResourceManager.GetString("ToursPanoramaPageHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TourTypeLabel {
            get {
                return ResourceManager.GetString("TourTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tracking.
        /// </summary>
        public static string TrackingPanoramaItemTitle {
            get {
                return ResourceManager.GetString("TrackingPanoramaItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the preferred unit of length for export and visual output..
        /// </summary>
        public static string UnitOfLengthDescriptionText {
            get {
                return ResourceManager.GetString("UnitOfLengthDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of length.
        /// </summary>
        public static string UnitOfLengthSettingsText {
            get {
                return ResourceManager.GetString("UnitOfLengthSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        public static string VehicleLabel {
            get {
                return ResourceManager.GetString("VehicleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vehicles.
        /// </summary>
        public static string VehiclesPanoramaPageHeaderText {
            get {
                return ResourceManager.GetString("VehiclesPanoramaPageHeaderText", resourceCulture);
            }
        }
    }
}
